// ─── AI Narrative Route ────────────────────────────────────────────────────────
// GET /api/reports/narrative?clientId=&from=&to=
//
// Returns a plain-English 3-sentence summary of the client's financial position,
// generated by Claude Haiku via Anthropic API.
//
// CACHING: Once per calendar day per client (Philippine time UTC+8).
// The narrative is cached in the clients table columns:
//   narrative_cache      TEXT  — the generated text
//   narrative_cached_at  TEXT  — ISO timestamp of when it was generated
//
// If ANTHROPIC_API_KEY is not set, returns a placeholder message.
// If API call fails, returns cached text or a safe fallback (never crashes).

import { Router } from 'express';
import { db, rowToClient } from '../db.js';
import { authenticate } from '../middleware/auth.js';

const router = Router();
router.use(authenticate);

const stmtClientById = db.prepare('SELECT * FROM clients WHERE id = ?');

// Add cache columns if they don't exist yet (safe to run on every startup)
try {
  db.exec("ALTER TABLE clients ADD COLUMN narrative_cache TEXT");
} catch { /* already exists */ }
try {
  db.exec("ALTER TABLE clients ADD COLUMN narrative_cached_at TEXT");
} catch { /* already exists */ }

const stmtSaveNarrative = db.prepare(
  'UPDATE clients SET narrative_cache=@cache, narrative_cached_at=@cachedAt WHERE id=@id'
);

function canAccess(client, userId) {
  return client.ownerId === userId || client.accountantId === userId ||
         (client.encoderIds || []).includes(userId);
}

// Philippine time date string "2026-07-01"
function phDate() {
  const now = new Date();
  const ph  = new Date(now.getTime() + 8 * 60 * 60 * 1000);
  return ph.toISOString().substring(0, 10);
}

function peso(n) {
  return '₱' + Number(n || 0).toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

// ── Fetch income/expense data for the period ───────────────────────────────────
function getPeriodData(clientId, from, to) {
  const base = `
    SELECT
      COALESCE(SUM(CASE WHEN type='income'  THEN amount_net  ELSE 0 END), 0) AS revenue,
      COALESCE(SUM(CASE WHEN type='expense' THEN amount_net  ELSE 0 END), 0) AS expenses,
      COALESCE(SUM(CASE WHEN type='income'  THEN amount_vat  ELSE 0 END), 0) AS output_vat,
      COALESCE(SUM(CASE WHEN type='expense' THEN amount_vat  ELSE 0 END), 0) AS input_vat,
      COUNT(*) AS tx_count
    FROM transactions
    WHERE client_id=? AND voided_at IS NULL
  `;
  const args = [clientId];
  let query  = base;
  if (from) { query += ' AND date(created_at) >= ?'; args.push(from); }
  if (to)   { query += ' AND date(created_at) <= ?'; args.push(to);   }
  return db.prepare(query).get(...args) || {};
}

function getARTotal(clientId) {
  try {
    return db.prepare(`
      SELECT COALESCE(SUM(total_amount), 0) AS ar
      FROM invoices
      WHERE client_id=? AND status NOT IN ('paid','void')
    `).get(clientId)?.ar || 0;
  } catch { return 0; }
}

// ── Claude API call (native fetch, no SDK) ─────────────────────────────────────
async function callClaude(prompt) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return null;

  const resp = await fetch('https://api.anthropic.com/v1/messages', {
    method:  'POST',
    headers: {
      'Content-Type':      'application/json',
      'x-api-key':         apiKey,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model:      'claude-haiku-4-5-20251001',
      max_tokens: 200,
      messages:   [{ role: 'user', content: prompt }],
    }),
  });

  if (!resp.ok) {
    console.error('Anthropic API error:', resp.status, await resp.text());
    return null;
  }

  const data = await resp.json();
  return data?.content?.[0]?.text?.trim() || null;
}

// ── Build prompt ──────────────────────────────────────────────────────────────
function buildPrompt(client, data, ar, from, to) {
  const profit     = (data.revenue || 0) - (data.expenses || 0);
  const vatPayable = Math.max(0, (data.output_vat || 0) - (data.input_vat || 0));
  const margin     = data.revenue > 0 ? Math.round((profit / data.revenue) * 100) : 0;
  const period     = from && to ? `${from} to ${to}` : 'this period';

  return `You are a friendly financial advisor for a Philippine small business called "${client.tradeName}".
Here are their numbers for ${period}:
- Net Revenue: ${peso(data.revenue)}
- Net Expenses: ${peso(data.expenses)}
- Net Profit/Loss: ${peso(profit)} (${margin}% margin)
- VAT Payable to BIR: ${peso(vatPayable)} (Output VAT minus Input VAT credit)
- Unpaid Invoices (AR): ${peso(ar)}
- Total Transactions: ${data.tx_count || 0}

Write exactly 3 short sentences in plain English for the business owner. Cover:
1. Whether the business is profitable this period
2. The VAT obligation or any amount to set aside for BIR
3. One practical action to improve cash or collections

Rules: No accounting jargon. Friendly, direct tone. Write in Filipino-English style. No bullet points, just 3 sentences in a paragraph. Keep it under 80 words.`;
}

// ═══════════════════════════════════════════════════════════════════════════════
// GET /api/reports/narrative
// ═══════════════════════════════════════════════════════════════════════════════
router.get('/', async (req, res, next) => {
  try {
    const { clientId, from, to } = req.query;
    if (!clientId) return res.status(400).json({ error: 'clientId is required' });

    const clientRow = stmtClientById.get(clientId);
    const client    = clientRow ? rowToClient(clientRow) : null;
    if (!client || !canAccess(client, req.userId))
      return res.status(404).json({ error: 'Client not found' });

    const today = phDate();

    // ── Serve cache if still valid (same PH calendar day) ──────────────────────
    const cachedDate = clientRow.narrative_cached_at?.substring(0, 10);
    if (cachedDate === today && clientRow.narrative_cache) {
      return res.json({
        narrative:  clientRow.narrative_cache,
        cachedAt:   clientRow.narrative_cached_at,
        fromCache:  true,
      });
    }

    // ── Generate fresh narrative ───────────────────────────────────────────────
    const data   = getPeriodData(clientId, from, to);
    const ar     = getARTotal(clientId);
    const prompt = buildPrompt(client, data, ar, from, to);

    let narrative = await callClaude(prompt);

    // Fallback if API unavailable
    if (!narrative) {
      const profit = (data.revenue || 0) - (data.expenses || 0);
      if (!process.env.ANTHROPIC_API_KEY) {
        narrative = `AI summaries require an ANTHROPIC_API_KEY to be set on the server. Ask your system administrator to configure it.`;
      } else {
        // API failed but key exists — use simple computed fallback
        const status = profit >= 0 ? `a profit of ${peso(profit)}` : `a loss of ${peso(Math.abs(profit))}`;
        narrative = `Your business recorded ${status} this period with net revenue of ${peso(data.revenue)}. Please check your VAT balance and ensure BIR filings are up to date. Review your unpaid invoices (${peso(ar)}) and follow up with customers to improve cash flow.`;
      }
    }

    // ── Cache the result ───────────────────────────────────────────────────────
    const cachedAt = new Date().toISOString();
    stmtSaveNarrative.run({ id: clientId, cache: narrative, cachedAt });

    res.json({ narrative, cachedAt, fromCache: false });

  } catch (err) { next(err); }
});

export default router;
